### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DrRuhe** [DrRuhe/nix2dream#1]
# Modules
These service level modules should allow more use-cases to be fulfilled by nix2dream
- [ ] permissions for folders
- [ ] users and groups 

# Renderers (And managers)
- [x] procfile
    - [x] hivemind 
    - [x] honcho 
- [ ] systemd
    - [ ] nixOS module 
    - [ ] systemd user units
- [x] docker-containers 
   - [x] skopeo for pushing to registries
   - [ ] docker-compose
   - [ ] kubernetes 

# API Improvements
- [ ] renderers and managers warn if options are set they don't support
- [ ] allow specifying extra renderer and manager modules once instead of having to import in every service/depoyment.
- [ ] figure out how to run one of the services locally, or how to attach a debugger to the service. This would be great for local development, as it would allow locally testing the service in the same environment it is supposed to run in anyway.  
- [ ] Expose the drv-parts documentation output for auto-generated documentation on which modules are available. Alternatively provide an doc output from the flake-parts module and its options.

# Miscellaneous
- [ ] #3
